import pytest
from jeu_vie import *

s : str ='''4 8
....
....
....
.**.
....
....
....
....'''


grille = Grille ()
grille.from_string(s)

def test_init () -> None:
    assert grille.width == 4 and grille.height == 8
    assert (grille.is_alive(1,3))
    assert (not grille.is_alive(0,0))

def test_count_neighboors():
    assert grille.count_neighboors(0,0) == 0
    assert grille.count_neighboors(1,3) == 1
    assert grille.count_neighboors(1,2) == 2

s_glider1 : str = '''8 8
........
.*......
..*.....
***.....
........
........
........
........'''

s_glider2 : str = '''8 8
........
........
*.*.....
.**.....
.*......
........
........
........'''

g_glider1 = Grille ()
g_glider2 = Grille ()

g_glider1.from_string(s_glider1)
g_glider2.from_string(s_glider2)

def test_update_state():
    g_glider1.update_state()
    assert (g_glider1.table == g_glider2.table)
